# TCP port for this node
port = 6002

# Content topic that all nodes will listen to
content-topic = "/intent-node/1/"

# Enable the store protocol
store = true

# Bootstrap static nodes - multiaddresses of the other nodes
staticnodes = [
    "/ip4/0.0.0.0/tcp/6003/p2p/PEER_ID_1"
]